const screens = ['Riepilogo','Ordini e margini','Costi','Resi','Importazioni','Da controllare','Impostazioni'];
const icons = ['⌂','#','€','↩','⇧','!','⚙'];
const nav = document.querySelector('#nav');
const title = document.querySelector('#title');
const content = document.querySelector('#content');
let dashboard=null;
let operations=null;
let operationsLoading=false;
let currentScreen='Riepilogo';
const orderFilters={search:'',month:'all',carrier:'all',status:'all'};
const costFilters={search:'',month:'all',type:'all'};
const returnFilters={search:'',month:'all',status:'all'};
const controlFilters={search:'',code:'all',severity:'all'};

screens.forEach((screen,index)=>{const button=document.createElement('button');button.textContent=`${icons[index]}  ${screen}`;button.addEventListener('click',()=>show(screen));nav.append(button)});

const kpi=(label,value,note)=>`<article class="kpi card"><small>${label}</small><strong>${value}</strong><em>${note}</em></article>`;
const toolbar=(extra='')=>`<div class="toolbar"><input aria-label="Cerca" placeholder="Cerca ordine, SKU o documento…"><select><option>Settembre 2026</option><option>Agosto 2026</option><option>Luglio 2026</option></select>${extra}<select><option>Tutti gli stati</option><option>Definitivo</option><option>Provvisorio</option><option>Sospeso</option></select></div>`;
const emptyRow=(columns)=>`<tr><td class="muted">Nessun dato importato</td>${'<td>—</td>'.repeat(columns-1)}</tr>`;
const money=(value)=>value!==null&&value!==undefined&&Number.isFinite(Number(value))?new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(value)):'—';
const percent=(value)=>value!==null&&value!==undefined&&Number.isFinite(Number(value))?`${Number(value).toLocaleString('it-IT',{maximumFractionDigits:2})}%`:'—';
const statusPill=(status)=>`<span class="pill ${status==='suspended'?'red':status==='provisional'?'amber':'green'}">${status==='suspended'?'Sospeso':status==='provisional'?'Provvisorio':'Definitivo'}</span>`;

function orderRows(orders,limit=10){
  if(!orders?.length)return emptyRow(9);
  return orders.slice(0,limit).map((order)=>`<tr><td><button class="order-link" data-order-id="${escapeHtml(order.marketplaceOrderId)}">${escapeHtml(order.marketplaceOrderId||'—')}</button></td><td>${order.date}</td><td>${escapeHtml(order.carrier||'—')}</td><td>${money(order.revenue)}</td><td>${money(-(order.product_cost||0))}</td><td>${money(-(order.shipping||0))}</td><td>${money(-(order.marketplace_fee||0))}</td><td>${money(order.margin)}</td><td>${statusPill(order.status)}</td></tr>`).join('');
}

function summaryScreen(){const s=dashboard?.summary;const last=dashboard?.daily?.at(-1);const daily=dashboard?.daily?.length?dashboard.daily.slice(-10).reverse().map((row)=>`<tr><td>${row.date}</td><td>${money(row.revenueEur)}</td><td>${money(row.marginEur)}</td><td>${row.orders} ordini</td></tr>`).join(''):emptyRow(4);const monthly=dashboard?.monthly?.length?dashboard.monthly.map((row)=>`<tr><td>${row.month}</td><td>${money(row.revenueEur)}</td><td>${money(row.marginEur)}</td><td>${s.returns}</td></tr>`).join(''):emptyRow(4);return `${toolbar()}<div class="kpis">${kpi('Fatturato',money(s?.revenueEur),dashboard?`${s.totalOrders} ordini Invoice`:'Da Invoice Back Market')}${kpi('Margine complessivo',money(s?.companyMarginEur),dashboard?'Include rimborsi e recuperi':'Copertura sempre visibile')}${kpi('Margine ultimo giorno',money(last?.marginEur),last?.date||'Nessun ricalcolo')}${kpi('Resi collegati',dashboard?`${s.linkedReturns} / ${s.returns}`:'—','Collegamenti conservativi')}</div><div class="summary-grid"><section class="card table-card"><div class="table-title"><strong>Andamento giornaliero</strong><span>Fatturato e margine</span></div><table><thead><tr><th>Giorno</th><th>Fatturato</th><th>Margine</th><th>Copertura</th></tr></thead><tbody>${daily}</tbody></table></section><section class="card table-card"><div class="table-title"><strong>Andamento mensile</strong><span>Confronto essenziale</span></div><table><thead><tr><th>Mese</th><th>Fatturato</th><th>Margine vendite</th><th>Resi</th></tr></thead><tbody>${monthly}</tbody></table></section></div><section class="card table-card spaced"><div class="table-title"><strong>Ultimi ordini</strong><span>Apri un ordine per vedere fonti e calcolo</span></div><table><thead><tr><th>Ordine</th><th>Data</th><th>Vettore</th><th>Ricavo</th><th>Prodotto</th><th>Spedizione</th><th>Commissioni</th><th>Margine</th><th>Stato</th></tr></thead><tbody>${orderRows(dashboard?.latestOrders,10)}</tbody></table></section>`}

function filteredOrders(){const query=orderFilters.search.trim().toLowerCase();return (dashboard?.latestOrders??[]).filter((order)=>(!query||String(order.marketplaceOrderId).toLowerCase().includes(query))&&(orderFilters.month==='all'||order.date.startsWith(orderFilters.month))&&(orderFilters.carrier==='all'||order.carrier===orderFilters.carrier)&&(orderFilters.status==='all'||order.status===orderFilters.status))}
function ordersToolbar(){const orders=dashboard?.latestOrders??[];const options=(values,current)=>values.map((value)=>`<option value="${escapeHtml(value)}" ${value===current?'selected':''}>${escapeHtml(value)}</option>`).join('');const months=[...new Set(orders.map((order)=>order.date.slice(0,7)))].sort().reverse();const carriers=[...new Set(orders.map((order)=>order.carrier).filter(Boolean))].sort();return `<div class="toolbar"><input id="order-search" aria-label="Cerca ordine" placeholder="Cerca numero ordine…" value="${escapeHtml(orderFilters.search)}"><select id="order-month"><option value="all">Tutti i periodi</option>${options(months,orderFilters.month)}</select><select id="order-carrier"><option value="all">Tutti i vettori</option>${options(carriers,orderFilters.carrier)}</select><select id="order-status"><option value="all">Tutti gli stati</option><option value="final" ${orderFilters.status==='final'?'selected':''}>Definitivo</option><option value="provisional" ${orderFilters.status==='provisional'?'selected':''}>Provvisorio</option><option value="suspended" ${orderFilters.status==='suspended'?'selected':''}>Sospeso</option></select></div>`}
function ordersScreen(){const s=dashboard?.summary;const avg=s?.coveredOrders?s.salesMarginEur/s.coveredOrders:null;const orders=filteredOrders();return `${ordersToolbar()}<div class="kpis">${kpi('Ordini',s?.totalOrders??'—','Nel periodo')}${kpi('Margine medio',money(avg),'Per ordine coperto')}${kpi('Copertura costi',percent(s?.percent),'Nessun costo inventato')}${kpi('Sospesi',s?.suspendedOrders??'—','Costo o collegamento mancante')}</div><section class="card table-card"><div class="table-title"><strong>Margine per ordine</strong><span id="orders-count">Mostrati ${Math.min(orders.length,100)} di ${orders.length}</span></div><table><thead><tr><th>Ordine</th><th>Data</th><th>Vettore</th><th>Fatturato</th><th>Costo prodotto</th><th>Spedizione</th><th>Commissioni</th><th>Margine</th><th>Stato</th></tr></thead><tbody id="orders-body">${orderRows(orders,100)}</tbody></table></section>`}

const costTypeLabels={purchase:'Acquisti',ready_purchase_price:'P.Acq.',ready_fifo:'FIFO'};
const linkStatusLabels={linked:'Collegato',unmatched:'Non collegato',candidate:'Candidato',ambiguous:'Ambiguo',rejected:'Rifiutato',manual:'Manuale'};
const loadingOperations=()=>'<section class="card"><div class="empty"><strong>Caricamento dati operativi…</strong>Sto preparando righe e provenienza dal database locale.</div></section>';
const monthOptions=(rows,dateKey,current)=>[...new Set(rows.map((row)=>row[dateKey]?.slice(0,7)).filter(Boolean))].sort().reverse().map((value)=>`<option value="${value}" ${value===current?'selected':''}>${value}</option>`).join('');

function filteredCosts(){const query=costFilters.search.trim().toLowerCase();return (operations?.costs??[]).filter((row)=>(!query||String(row.productCode).toLowerCase().includes(query)||String(row.provenance?.sourceName||'').toLowerCase().includes(query))&&(costFilters.month==='all'||row.availableOn.startsWith(costFilters.month))&&(costFilters.type==='all'||row.costType===costFilters.type))}
function costRows(rows){return rows.length?rows.slice(0,100).map((row)=>`<tr><td>${row.availableOn}</td><td><strong>${escapeHtml(row.productCode||'—')}</strong></td><td>${escapeHtml(costTypeLabels[row.costType]||row.costType)}</td><td>${Number(row.quantity).toLocaleString('it-IT')}</td><td>${money(row.unitCostEur)}</td><td><small>${provenance(row)}</small></td></tr>`).join(''):emptyRow(6)}
function costsScreen(){const s=dashboard?.summary;const total=s?s.productCostEur+s.shippingEur+s.marketplaceFeesEur+s.investorFeesEur+s.storfundFeesEur:null;if(!operations)return `${kpi('Costi vendite',money(total),'Ordini coperti')}${loadingOperations()}`;const rows=filteredCosts();return `<div class="toolbar"><input id="cost-search" aria-label="Cerca costo" placeholder="Cerca codice prodotto o file…" value="${escapeHtml(costFilters.search)}"><select id="cost-month"><option value="all">Tutti i periodi</option>${monthOptions(operations.costs,'availableOn',costFilters.month)}</select><select id="cost-type"><option value="all">Tutte le fonti costo</option>${Object.entries(costTypeLabels).map(([value,label])=>`<option value="${value}" ${value===costFilters.type?'selected':''}>${label}</option>`).join('')}</select></div><div class="kpis">${kpi('Costi vendite',money(total),'Ordini coperti')}${kpi('Costo prodotto',money(s?.productCostEur),'Gerarchia temporale applicata')}${kpi('Commissioni',money(s?.marketplaceFeesEur),'Da Invoice')}${kpi('Spedizione',money(s?.shippingEur),'Una per ordine')}</div><section class="card table-card"><div class="table-title"><strong>Fonti costo prodotto</strong><span id="cost-count">Mostrate ${Math.min(rows.length,100)} di ${rows.length}</span></div><table><thead><tr><th>Disponibile dal</th><th>Prodotto</th><th>Fonte</th><th>Quantità</th><th>Costo unitario</th><th>Provenienza</th></tr></thead><tbody id="cost-body">${costRows(rows)}</tbody></table></section>`}

function filteredReturns(){const query=returnFilters.search.trim().toLowerCase();return (operations?.returns??[]).filter((row)=>(!query||[row.documentNumber,row.productCode,row.marketplaceOrderId,row.reason,row.provenance?.sourceName].some((value)=>String(value||'').toLowerCase().includes(query)))&&(returnFilters.month==='all'||row.documentDate.startsWith(returnFilters.month))&&(returnFilters.status==='all'||row.linkStatus===returnFilters.status))}
function returnRows(rows){return rows.length?rows.slice(0,100).map((row)=>`<tr><td>${row.documentDate}</td><td><strong>${escapeHtml(row.documentNumber)}</strong><small>${escapeHtml(row.marketplaceOrderId?`Rif. ordine ${row.marketplaceOrderId}`:'Riferimento ordine non presente')}</small></td><td><strong>${escapeHtml(row.productCode||'—')}</strong><small>${escapeHtml(row.reason?`Motivo: ${row.reason}`:'Motivo non indicato')}</small></td><td>${Number(row.quantity).toLocaleString('it-IT')} × ${money(row.unitPrice)}</td><td><span class="pill ${row.linkStatus==='linked'?'green':'amber'}">${escapeHtml(linkStatusLabels[row.linkStatus]||row.linkStatus)}</span><small>${escapeHtml(row.linkReason||'')}</small></td><td><small>${provenance(row)}</small></td></tr>`).join(''):emptyRow(6)}
function returnsScreen(){const s=dashboard?.summary;const unlinked=(s?.returns??0)-(s?.linkedReturns??0);if(!operations)return loadingOperations();const rows=filteredReturns();return `<div class="toolbar"><input id="return-search" aria-label="Cerca reso" placeholder="Cerca documento, ordine o prodotto…" value="${escapeHtml(returnFilters.search)}"><select id="return-month"><option value="all">Tutti i periodi</option>${monthOptions(operations.returns,'documentDate',returnFilters.month)}</select><select id="return-status"><option value="all">Tutti gli stati</option>${[...new Set(operations.returns.map((row)=>row.linkStatus))].map((value)=>`<option value="${value}" ${value===returnFilters.status?'selected':''}>${escapeHtml(linkStatusLabels[value]||value)}</option>`).join('')}</select></div><div class="kpis">${kpi('Resi',s?.returns??'—','Nel file Ready')}${kpi('Collegati',s?.linkedReturns??'—','Ordine e prodotto verificati')}${kpi('Da controllare',dashboard?unlinked:'—','Nessun legame forzato')}${kpi('Valore rientrato','—','Solo dopo verifica storica')}</div><section class="card table-card"><div class="table-title"><strong>Resi e collegamenti</strong><span id="return-count">Mostrati ${Math.min(rows.length,100)} di ${rows.length}</span></div><table><thead><tr><th>Data</th><th>Documento</th><th>Prodotto</th><th>Quantità e prezzo</th><th>Collegamento</th><th>Provenienza</th></tr></thead><tbody id="return-body">${returnRows(rows)}</tbody></table></section>`}

function filteredControls(){const query=controlFilters.search.trim().toLowerCase();return (operations?.anomalies??[]).filter((row)=>(!query||[row.reference,row.productCode,row.message,row.code,row.provenance?.sourceName].some((value)=>String(value||'').toLowerCase().includes(query)))&&(controlFilters.code==='all'||row.code===controlFilters.code)&&(controlFilters.severity==='all'||row.severity===controlFilters.severity))}
function controlRows(rows){return rows.length?rows.slice(0,100).map((row)=>`<tr><td><span class="pill ${row.severity==='blocking'?'red':'amber'}">${row.severity==='blocking'?'Bloccante':'Avviso'}</span></td><td><strong>${escapeHtml(row.code)}</strong><small>${escapeHtml(row.message)}</small></td><td>${escapeHtml(row.reference||'—')}<small>${escapeHtml(row.productCode||'')}</small></td><td><small>${row.provenance?provenance(row):'Generata dal calcolo'}</small></td></tr>`).join(''):emptyRow(4)}
function controlsScreen(){const a=dashboard?.anomalyCounts??{};const blocking=(a.MISSING_COST??0)+(a.MISSING_CARRIER??0)+(a.AMBIGUOUS_CARRIER??0)+(a.UNLINKED_ORDER??0);if(!operations)return loadingOperations();const rows=filteredControls();const codes=[...new Set(operations.anomalies.map((row)=>row.code))].sort();return `<div class="toolbar"><input id="control-search" aria-label="Cerca controllo" placeholder="Cerca ordine, prodotto o controllo…" value="${escapeHtml(controlFilters.search)}"><select id="control-code"><option value="all">Tutti i controlli</option>${codes.map((value)=>`<option value="${value}" ${value===controlFilters.code?'selected':''}>${escapeHtml(value)}</option>`).join('')}</select><select id="control-severity"><option value="all">Tutte le priorità</option><option value="blocking" ${controlFilters.severity==='blocking'?'selected':''}>Bloccanti</option><option value="warning" ${controlFilters.severity==='warning'?'selected':''}>Avvisi</option></select></div><div class="kpis">${kpi('Bloccanti',dashboard?blocking:'—','Numeri esclusi dai totali')}${kpi('Costo mancante',a.MISSING_COST??0,'Ordini sospesi')}${kpi('Resi non collegati',a.UNLINKED_RETURN??0,'Revisione manuale')}${kpi('Non classificati',a.UNCLASSIFIED_MOVEMENT??0,'Movimenti Invoice')}</div><section class="card table-card"><div class="table-title"><strong>Controlli aperti</strong><span id="control-count">Mostrati ${Math.min(rows.length,100)} di ${rows.length}</span></div><table><thead><tr><th>Priorità</th><th>Controllo</th><th>Riferimento</th><th>Provenienza</th></tr></thead><tbody id="control-body">${controlRows(rows)}</tbody></table></section>`}

function importsScreen(){return `<div class="import-grid"><section class="card import-form"><div class="steps"><span class="step current">1 Anteprima</span><span class="step">2 Validazione</span><span class="step">3 Conferma</span></div><h2>Importa CSV sul database locale</h2><label for="csv-files">Seleziona uno o più file</label><input id="csv-files" type="file" accept=".csv,text/csv" multiple><p class="footnote">La fonte viene riconosciuta dalle intestazioni. Il file non entra nel repository e l’anteprima non scrive nel database.</p><button class="primary" id="preview">Analizza file</button></section><aside class="card help"><h3>Controlli essenziali</h3><ul><li>intestazioni e tipi</li><li>hash del file e riga fisica</li><li>dati mancanti o non classificati</li><li>conferma manuale, mai automatica</li></ul><p id="import-message" class="footnote">Pronto per una prova locale.</p></aside></div><section class="card table-card spaced"><div class="table-title"><strong>Anteprime</strong><span id="preview-count">Nessun file analizzato</span></div><div id="import-results" class="import-results"><div class="empty"><strong>Nessuna anteprima</strong>Seleziona i CSV e analizzali insieme.</div></div></section>`}

const sourceLabels={invoice:'Invoice Back Market',orders:'Export ordini Back Market',ready_sales:'Vendite Ready',purchases:'Costi / Acquisti',ready_returns:'Resi Ready'};
const escapeHtml=(value)=>String(value).replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const errorLabels={UNKNOWN_SOURCE_HEADERS:'Intestazioni non riconosciute',FILE_TOO_LARGE:'File troppo grande',EMPTY_FILE:'File vuoto',INVALID_JSON:'Richiesta non valida',PREVIEW_EXPIRED:'Anteprima scaduta: analizza di nuovo il file',PREVIEW_HASH_MISMATCH:'Il contenuto non corrisponde più all’anteprima',PREVIEW_HAS_ERRORS:'Correggi gli errori prima di confermare',LOCAL_SUPABASE_UNAVAILABLE:'Supabase locale non è avviato',LOCAL_SUPABASE_CREDENTIALS_UNAVAILABLE:'Configurazione Supabase locale non disponibile',REMOTE_SUPABASE_BLOCKED:'L’operatore locale rifiuta connessioni a Supabase remoto',LOCAL_DATABASE_ERROR:'Errore del database locale'};
const importState=[];

function importCard(item){
  if(item.error)return `<article class="import-result error"><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(errorLabels[item.error]||item.error)}</span></article>`;
  const p=item.preview;const issueText=p.issues.length?`${p.issues.length} anomalie mostrate su massimo 20`:'Nessuna anomalia';
  const action=p.saved?`<span class="pill green">${p.inserted?'Importato':'Già presente'}</span>`:p.canConfirm?`<button class="confirm-import" data-preview-id="${p.previewId}" data-hash="${p.contentSha256}">Conferma nel database locale</button>`:`<span class="pill red">Correzione necessaria</span>`;
  return `<article class="import-result"><div><strong>${escapeHtml(p.sourceName)}</strong><small>${escapeHtml(sourceLabels[p.source]||p.source)} · righe ${p.rowCount}</small></div><div class="import-metrics"><span>Valide <b>${p.validCount}</b></span><span>Errori <b>${p.errorCount}</b></span><span>Avvisi <b>${p.warningCount}</b></span><span>Ignorate <b>${p.ignoredCount}</b></span></div><small>${issueText}</small><div>${action}</div></article>`;
}

function renderImports(){
  const results=document.querySelector('#import-results');if(!results)return;
  results.innerHTML=importState.length?importState.map(importCard).join(''):`<div class="empty"><strong>Nessuna anteprima</strong>Seleziona i CSV e analizzali insieme.</div>`;
  document.querySelector('#preview-count').textContent=importState.length?`${importState.length} file analizzati`:'Nessun file analizzato';
}

async function parseResponse(response){const payload=await response.json().catch(()=>({error:'INVALID_RESPONSE'}));if(!response.ok)throw new Error(payload.error||'REQUEST_FAILED');return payload}

function setupImports(){
  document.querySelector('#preview')?.addEventListener('click',async()=>{
    const files=[...(document.querySelector('#csv-files')?.files||[])];const message=document.querySelector('#import-message');
    if(!files.length){message.textContent='Seleziona almeno un file CSV.';return}
    message.textContent=`Analisi di ${files.length} file in corso…`;importState.length=0;renderImports();
    for(const file of files){
      try{
        const response=await fetch('/api/imports/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceName:file.name,content:await file.text()})});
        importState.push({name:file.name,preview:await parseResponse(response)});
      }catch(error){importState.push({name:file.name,error:error.message})}
      renderImports();
    }
    message.textContent='Anteprima completata. Controlla i conteggi prima di confermare.';
  });
  document.querySelector('#import-results')?.addEventListener('click',async(event)=>{
    const button=event.target.closest('.confirm-import');if(!button)return;
    button.disabled=true;button.textContent='Conferma in corso…';
    try{
      const response=await fetch('/api/imports/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({previewId:button.dataset.previewId,contentSha256:button.dataset.hash})});
      const saved=await parseResponse(response);const item=importState.find((entry)=>entry.preview?.previewId===button.dataset.previewId);Object.assign(item.preview,{saved:true,...saved});renderImports();
      document.querySelector('#import-message').textContent=saved.inserted?'Batch salvato nel database locale.':'Questo identico file era già presente: nessuna duplicazione.';
    }catch(error){button.disabled=false;button.textContent='Riprova conferma';document.querySelector('#import-message').textContent=errorLabels[error.message]||error.message}
  });
}

function setupOrderFilters(){
  const refresh=()=>{const orders=filteredOrders();const body=document.querySelector('#orders-body');const count=document.querySelector('#orders-count');if(body)body.innerHTML=orderRows(orders,100);if(count)count.textContent=`Mostrati ${Math.min(orders.length,100)} di ${orders.length}`};
  document.querySelector('#order-search')?.addEventListener('input',(event)=>{orderFilters.search=event.target.value;refresh()});
  for(const [id,key] of [['order-month','month'],['order-carrier','carrier'],['order-status','status']])document.querySelector(`#${id}`)?.addEventListener('change',(event)=>{orderFilters[key]=event.target.value;refresh()});
}

function setupOperationalFilters(kind){
  const configs={
    cost:{search:['cost-search',costFilters,'search'],selects:[['cost-month',costFilters,'month'],['cost-type',costFilters,'type']],body:'cost-body',count:'cost-count',filter:filteredCosts,rows:costRows,label:'Mostrate'},
    return:{search:['return-search',returnFilters,'search'],selects:[['return-month',returnFilters,'month'],['return-status',returnFilters,'status']],body:'return-body',count:'return-count',filter:filteredReturns,rows:returnRows,label:'Mostrati'},
    control:{search:['control-search',controlFilters,'search'],selects:[['control-code',controlFilters,'code'],['control-severity',controlFilters,'severity']],body:'control-body',count:'control-count',filter:filteredControls,rows:controlRows,label:'Mostrati'}
  };
  const config=configs[kind];if(!config)return;
  const refresh=()=>{const rows=config.filter();const body=document.querySelector(`#${config.body}`);const count=document.querySelector(`#${config.count}`);if(body)body.innerHTML=config.rows(rows);if(count)count.textContent=`${config.label} ${Math.min(rows.length,100)} di ${rows.length}`};
  const [searchId,state,key]=config.search;document.querySelector(`#${searchId}`)?.addEventListener('input',(event)=>{state[key]=event.target.value;refresh()});
  for(const [id,selectState,selectKey] of config.selects)document.querySelector(`#${id}`)?.addEventListener('change',(event)=>{selectState[selectKey]=event.target.value;refresh()});
}

async function ensureOperations(){
  if(operations||operationsLoading)return;operationsLoading=true;
  try{const payload=await parseResponse(await fetch('/api/operations'));operations=payload.operations;if(['Costi','Resi','Da controllare'].includes(currentScreen))show(currentScreen)}
  catch(error){const message=errorLabels[error.message]||error.message;content.innerHTML=`<section class="card"><div class="empty"><strong>Dati operativi non disponibili</strong>${escapeHtml(message)}</div></section>`}
  finally{operationsLoading=false}
}

const componentLabels={revenue:'Ricavo',marketplace_fee:'Commissioni marketplace',product_cost:'Costo prodotto',shipping:'Spedizione',investor_fee:'Investor Fee',storfund_fee:'Storfund Fee',margin:'Margine vendite'};
const categoryLabels={revenue:'Ricavo',marketplace_fee:'Commissione',refund:'Rimborso',recovery:'Recupero',shipping:'Spedizione',product_cost:'Costo prodotto',investor_fee:'Investor Fee',storfund_fee:'Storfund Fee',backship:'Spedizione di ritorno',epr:'EPR',subscription:'Abbonamento',returned_product_value:'Valore prodotto reso',other:'Altro'};
const originLabels={READY:'Vendite Ready',BACK_MARKET_RECONSTRUCTED:'Export ordini Back Market',UNRESOLVED:'Origine non risolta'};
const provenance=(item)=>item?.provenance?`${escapeHtml(item.provenance.sourceName)} · riga ${item.provenance.rowNumber}`:'Fonte non disponibile';
const costProvenance=(selection)=>{const sources=selection?.sources??[];if(!sources.length)return '';const shown=sources.slice(0,3).map(provenance).join('; ');return sources.length>3?`${shown}; +${sources.length-3} righe`:`${shown}`};

function ensureOrderDialog(){let dialog=document.querySelector('#order-dialog');if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='order-dialog';dialog.className='detail-dialog';dialog.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close()});document.body.append(dialog);return dialog}
function renderOrderDetail(detail){
  const dialog=ensureOrderDialog();const order=detail.order;
  const components=detail.components.length?detail.components.map((row)=>`<tr><td>${escapeHtml(componentLabels[row.component]||row.component)}</td><td>${money(row.amountEur)}</td><td>${statusPill(row.status)}</td></tr>`).join(''):emptyRow(3);
  const lines=detail.lines.length?detail.lines.map((line)=>`<tr><td><strong>${escapeHtml(line.product_code||line.sku||'—')}</strong><small>${escapeHtml(line.description||originLabels[line.line_origin]||'')}</small></td><td>${Number(line.quantity).toLocaleString('it-IT')}</td><td>${money(line.unit_price)}</td><td><strong>${escapeHtml(line.costSelection?.sourceLabel||'Non disponibile')}</strong><small>${money(line.costSelection?.unitCostEur)} per unità${costProvenance(line.costSelection)?` · ${costProvenance(line.costSelection)}`:''}</small></td><td>${escapeHtml(line.carrier||'—')}</td><td><small>${provenance(line)}</small></td></tr>`).join(''):emptyRow(6);
  const movements=detail.movements.length?detail.movements.map((row)=>`<tr><td>${row.value_date}</td><td><strong>${escapeHtml(categoryLabels[row.economic_category]||row.economic_category||row.movement_type)}</strong><small>${escapeHtml(row.designation||row.movement_type)}</small></td><td>${Number(row.amount).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2})} ${escapeHtml(row.currency)}</td><td>${money(row.amount_eur)}</td><td><small>${provenance(row)}</small></td></tr>`).join(''):emptyRow(5);
  dialog.innerHTML=`<div class="detail-head"><div><small>DETTAGLIO ORDINE</small><h2>${escapeHtml(order.marketplaceOrderId)}</h2><p>${escapeHtml((order.soldAt||'').slice(0,10))} · ${escapeHtml(order.carrier||'Vettore non disponibile')} · ${statusPill(order.status)}</p></div><button class="detail-close" aria-label="Chiudi">×</button></div><div class="detail-grid"><section><h3>Composizione del margine</h3><table><thead><tr><th>Voce</th><th>Importo</th><th>Stato</th></tr></thead><tbody>${components}</tbody></table></section><section><h3>Righe prodotto e costo scelto</h3><table><thead><tr><th>Prodotto</th><th>Qtà</th><th>Prezzo Ready</th><th>Fonte costo</th><th>Vettore</th><th>Provenienza</th></tr></thead><tbody>${lines}</tbody></table></section><section><h3>Movimenti Invoice</h3><table><thead><tr><th>Data</th><th>Movimento</th><th>Originale</th><th>EUR</th><th>Provenienza</th></tr></thead><tbody>${movements}</tbody></table></section></div><footer>Calcolo ${escapeHtml(detail.run.engineVersion)} · fonti tracciate fino alla riga CSV originale</footer>`;
  dialog.querySelector('.detail-close').addEventListener('click',()=>dialog.close());if(!dialog.open)dialog.showModal();
}
async function openOrderDetail(orderId){const dialog=ensureOrderDialog();dialog.innerHTML='<div class="detail-loading">Caricamento dettaglio…</div>';if(!dialog.open)dialog.showModal();try{const payload=await parseResponse(await fetch(`/api/orders/${encodeURIComponent(orderId)}`));renderOrderDetail(payload.detail)}catch(error){dialog.innerHTML=`<div class="detail-loading"><strong>Dettaglio non disponibile</strong><p>${escapeHtml(errorLabels[error.message]||error.message)}</p><button class="detail-close">Chiudi</button></div>`;dialog.querySelector('.detail-close').addEventListener('click',()=>dialog.close())}}

function settingsScreen(){const params=dashboard?.parameters??[];const latest=(key)=>params.filter((p)=>p.key===key).sort((a,b)=>b.valid_from.localeCompare(a.valid_from))[0];const rate=(key)=>{const p=latest(key);if(!p)return '—';return p.unit==='PERCENT_OF_SALES'?percent(Number(p.value)*100):money(p.value)};return `<div class="kpis">${kpi('DHL',rate('shipping_dhl'),'EUR per ordine')}${kpi('GLS',rate('shipping_gls'),'EUR per ordine')}${kpi('Investor Fee',rate('investor_fee'),'% vendite')}${kpi('Storfund Fee',rate('storfund_fee'),'% vendite')}</div><section class="card table-card"><div class="table-title"><strong>Parametri economici</strong><span>Valori con decorrenza</span></div><table><thead><tr><th>Parametro</th><th>Dal</th><th>Al</th><th>Valore</th><th>Nota</th></tr></thead><tbody>${params.length?params.map((p)=>`<tr><td>${escapeHtml(p.key)}</td><td>${p.valid_from}</td><td>${p.valid_to||'in corso'}</td><td>${p.unit==='PERCENT_OF_SALES'?percent(Number(p.value)*100):money(p.value)}</td><td>${escapeHtml(p.note)}</td></tr>`).join(''):emptyRow(5)}</tbody></table></section>`}

function show(screen){currentScreen=screen;title.textContent=screen;[...nav.children].forEach((button)=>button.classList.toggle('active',button.textContent.includes(screen)));const render={'Riepilogo':summaryScreen,'Ordini e margini':ordersScreen,'Costi':costsScreen,'Resi':returnsScreen,'Importazioni':importsScreen,'Da controllare':controlsScreen,'Impostazioni':settingsScreen};content.innerHTML=render[screen]();if(screen==='Importazioni'){importState.length=0;setupImports()}if(screen==='Ordini e margini')setupOrderFilters();if(screen==='Costi')setupOperationalFilters('cost');if(screen==='Resi')setupOperationalFilters('return');if(screen==='Da controllare')setupOperationalFilters('control');if(['Costi','Resi','Da controllare'].includes(screen))ensureOperations()}
async function refreshDashboard(){const response=await fetch('/api/dashboard');const payload=await parseResponse(response);dashboard=payload.dashboard;show(currentScreen)}
content.addEventListener('click',(event)=>{const button=event.target.closest('.order-link');if(button)openOrderDetail(button.dataset.orderId)});
document.querySelector('#recalculate').addEventListener('click',async(event)=>{const button=event.currentTarget;button.disabled=true;button.textContent='Ricalcolo…';try{await parseResponse(await fetch('/api/recalculate',{method:'POST'}));await refreshDashboard()}catch(error){alert(errorLabels[error.message]||error.message)}finally{button.disabled=false;button.textContent='Ricalcola'}});
show('Riepilogo');
refreshDashboard().catch(()=>{});
