const screens = ['Riepilogo','Ordini e margini','Costi','Resi','Importazioni','Da controllare','Impostazioni'];
const icons = ['⌂','#','€','↩','⇧','!','⚙'];
const nav = document.querySelector('#nav');
const title = document.querySelector('#title');
const content = document.querySelector('#content');

screens.forEach((screen,index)=>{const button=document.createElement('button');button.textContent=`${icons[index]}  ${screen}`;button.addEventListener('click',()=>show(screen));nav.append(button)});

const kpi=(label,value,note)=>`<article class="kpi card"><small>${label}</small><strong>${value}</strong><em>${note}</em></article>`;
const toolbar=(extra='')=>`<div class="toolbar"><input aria-label="Cerca" placeholder="Cerca ordine, SKU o documento…"><select><option>Settembre 2026</option><option>Agosto 2026</option><option>Luglio 2026</option></select>${extra}<select><option>Tutti gli stati</option><option>Definitivo</option><option>Provvisorio</option><option>Sospeso</option></select></div>`;
const emptyRow=(columns)=>`<tr><td class="muted">Nessun dato importato</td>${'<td>—</td>'.repeat(columns-1)}</tr>`;

function summaryScreen(){return `${toolbar()}<div class="kpis">${kpi('Fatturato','—','Da Invoice Back Market')}${kpi('Margine complessivo','—','Copertura sempre visibile')}${kpi('Margine del giorno','—','Nessun dato reale')}${kpi('Resi collegati','—','Ordine e prodotto')}</div><div class="summary-grid"><section class="card table-card"><div class="table-title"><strong>Andamento giornaliero</strong><span>Fatturato e margine</span></div><table><thead><tr><th>Giorno</th><th>Fatturato</th><th>Margine</th><th>Copertura</th></tr></thead><tbody>${emptyRow(4)}</tbody></table></section><section class="card table-card"><div class="table-title"><strong>Andamento mensile</strong><span>Confronto essenziale</span></div><table><thead><tr><th>Mese</th><th>Fatturato</th><th>Margine</th><th>Resi</th></tr></thead><tbody>${emptyRow(4)}</tbody></table></section></div><section class="card table-card spaced"><div class="table-title"><strong>Ultimi ordini</strong><span>Composizione del margine</span></div><table><thead><tr><th>Ordine</th><th>Ricavo</th><th>Prodotto</th><th>Spedizione</th><th>Commissioni</th><th>Margine</th><th>Stato</th></tr></thead><tbody>${emptyRow(7)}</tbody></table></section>`}

function ordersScreen(){return `${toolbar()}<div class="kpis">${kpi('Ordini','—','Nel periodo')}${kpi('Margine medio','—','Per ordine')}${kpi('Copertura costi','—','Nessun costo inventato')}${kpi('Sospesi','—','Costo o collegamento mancante')}</div><section class="card table-card"><div class="table-title"><strong>Margine per ordine</strong><span>Drill-down sulla provenienza</span></div><table><thead><tr><th>Ordine</th><th>Data</th><th>Fatturato</th><th>Costo prodotto</th><th>Spedizione</th><th>Commissioni</th><th>Margine</th><th>Stato</th></tr></thead><tbody>${emptyRow(8)}</tbody></table></section>`}

function costsScreen(){const category='<select><option>Tutte le categorie</option><option>Prodotto</option><option>Spedizione</option><option>Commissioni marketplace</option><option>Investor Fee</option><option>Storfund Fee</option><option>Rimborsi</option><option>Backship</option><option>EPR</option><option>Canoni</option><option>Altro</option></select>';return `${toolbar(category)}<div class="kpis">${kpi('Costi totali','—','Per data contabile')}${kpi('Costo prodotto','—','Regola temporale applicata')}${kpi('Commissioni','—','Da Invoice')}${kpi('Non classificati','—','Sempre da controllare')}</div><section class="card table-card"><div class="table-title"><strong>Costi classificati</strong><span>Categoria, fonte e ordine</span></div><table><thead><tr><th>Categoria</th><th>Data</th><th>Ordine</th><th>Descrizione</th><th>Fonte</th><th>Importo</th><th>Stato</th></tr></thead><tbody>${emptyRow(7)}</tbody></table></section>`}

function returnsScreen(){return `${toolbar()}<div class="kpis">${kpi('Resi','—','Nel periodo')}${kpi('Collegati','—','Ordine e prodotto verificati')}${kpi('Ambigui','—','Nessun legame forzato')}${kpi('Valore rientrato','—','Solo valore storico verificato')}</div><section class="card table-card"><div class="table-title"><strong>Resi e collegamenti</strong><span>Documento, prodotto, quantità e prezzo</span></div><table><thead><tr><th>Documento</th><th>Data</th><th>SKU</th><th>Quantità</th><th>Ordine collegato</th><th>Valore</th><th>Esito</th></tr></thead><tbody>${emptyRow(7)}</tbody></table></section>`}

function controlsScreen(){return `${toolbar('<select><option>Tutti i controlli</option><option>Costo mancante</option><option>Ordine non collegato</option><option>Movimento non classificato</option><option>Duplicato evidente</option><option>Provenienza mancante</option></select>')}<div class="kpis">${kpi('Bloccanti','—','Numeri esclusi dai totali')}${kpi('Costo mancante','—','Ordini sospesi')}${kpi('Non collegati','—','Ordini o resi')}${kpi('Non classificati','—','Movimenti Invoice')}</div><section class="card table-card"><div class="table-title"><strong>Da controllare</strong><span>Solo anomalie indispensabili</span></div><table><thead><tr><th>Controllo</th><th>Entità</th><th>Descrizione</th><th>Fonte/riga</th><th>Stato</th></tr></thead><tbody>${emptyRow(5)}</tbody></table></section>`}

function importsScreen(){return `<div class="import-grid"><section class="card import-form"><div class="steps"><span class="step current">1 Anteprima</span><span class="step">2 Validazione</span><span class="step">3 Conferma</span></div><h2>Importa da Google Sheets</h2><label for="source">Fonte</label><select id="source"><option>Invoice Back Market</option><option>Export ordini</option><option>Ready vendite</option><option>Costi / Acquisti</option><option>Ready Resi</option></select><label for="sheet">Link o ID del foglio</label><input id="sheet" placeholder="https://docs.google.com/spreadsheets/d/…"><label for="range">Intervallo</label><input id="range" value="Dati!A:Z"><p class="footnote">Nessuna chiave nel foglio e nessun import automatico.</p><button class="primary" id="preview">Crea anteprima</button></section><aside class="card help"><h3>Controlli essenziali</h3><ul><li>intestazioni e tipi</li><li>provenienza della riga</li><li>duplicati evidenti</li><li>chiavi e dati mancanti</li></ul><p id="import-message" class="footnote">Integrazione non configurata in questa fase.</p></aside></div>`}

function settingsScreen(){return `<div class="kpis">${kpi('DHL','—','EUR per ordine')}${kpi('GLS','—','EUR per ordine')}${kpi('Investor Fee','—','% vendite')}${kpi('Storfund Fee','—','% vendite')}</div><section class="card table-card"><div class="table-title"><strong>Parametri economici</strong><span>Valori con decorrenza</span></div><div class="empty"><strong>Nessun parametro configurato</strong>SEK 0,09 e gli altri valori saranno inseriti soltanto nello stack autorizzato.</div></section>`}

function show(screen){title.textContent=screen;[...nav.children].forEach((button)=>button.classList.toggle('active',button.textContent.includes(screen)));const render={'Riepilogo':summaryScreen,'Ordini e margini':ordersScreen,'Costi':costsScreen,'Resi':returnsScreen,'Importazioni':importsScreen,'Da controllare':controlsScreen,'Impostazioni':settingsScreen};content.innerHTML=render[screen]();document.querySelector('#preview')?.addEventListener('click',()=>{document.querySelector('#import-message').textContent='Anteprima non eseguita: servono autorizzazione e configurazione Google server-side.'})}
document.querySelector('#recalculate').addEventListener('click',()=>alert('Ricalcolo non eseguito: non esistono batch confermati.'));
show('Riepilogo');
